#!/usr/bin/env python3
"""Coverage report: template slots -> atoms -> credentials -> TEKS.

For each Texas course template, determines which TEKS are covered by at
least one slot and which TEKS have zero coverage. A TEKS is "covered"
if any atom in any slot maps (via its credential_objectives) to that
TEKS in the Texas crosswalk.
"""
import csv
import os
import re
from collections import defaultdict

BASE = "/home/user/CTE"
ATOM_DIR = f"{BASE}/library/atoms/it-support-services"
FRAMEWORK = f"{BASE}/library/credentials/clusters/digital-technology/it-support-services/crosswalks/texas/state-framework.csv"
CROSSWALK = f"{BASE}/library/credentials/clusters/digital-technology/it-support-services/crosswalks/texas/crosswalk.csv"
TPL_DIR = f"{BASE}/templates/texas/it-support-services"
OUT = f"{BASE}/crosswalks/texas-it-support-coverage-report.md"

TEMPLATES = {
    "130.302": "tx-principles-of-it-2025.md",
    "130.303": "tx-computer-maintenance-2025.md",
    "130.304": "tx-computer-maintenance-lab-2025.md",
}


def load_teks_by_course():
    by_course = defaultdict(list)
    texts = {}
    with open(FRAMEWORK) as f:
        for r in csv.DictReader(f):
            by_course[r["course_code"]].append(r["standard_code"])
            texts[r["standard_code"]] = r["standard_text"]
    return by_course, texts


def load_credential_to_teks():
    cred_to_teks = defaultdict(set)
    with open(CROSSWALK) as f:
        for r in csv.DictReader(f):
            cred_to_teks[r["atom_id"]].add(r["standard_code"])
    return cred_to_teks


def atom_credentials(atom_id):
    path = os.path.join(ATOM_DIR, atom_id + ".md")
    if not os.path.exists(path):
        return []
    with open(path) as f:
        txt = f.read()
    m = re.search(r"credential_objectives:(.*?)(?:\nskill_type:|\Z)", txt, re.S)
    if not m:
        return []
    block = m.group(1)
    return re.findall(r"-\s+([^\s\n]+)", block)


def template_atoms(template_path):
    with open(template_path) as f:
        txt = f.read()
    return re.findall(r"atom_id:\s+([\w-]+)", txt)


def main():
    teks_by_course, teks_text = load_teks_by_course()
    cred_to_teks = load_credential_to_teks()

    lines = [
        "# Texas IT Support — TEKS Coverage Report",
        "",
        "Derived coverage per course via the slot \u2192 atom \u2192 credential \u2192 TEKS chain.",
        "Generated by `scripts/coverage_report.py`.",
        "",
        "> **Interpreting low coverage:** if an atom obviously covers a TEKS yet that TEKS still shows as uncovered, the gap is in `crosswalk.csv`, not in the template. The crosswalk is still a partial AI draft pending Maya's review \u2014 many TEKS have no credential-objective mapping yet. Uncovered TEKS below fall into two buckets: (a) crosswalk rows missing (fix in crosswalk.csv), (b) atom missing from template or library (fix in template or author new atom).",
        "",
    ]

    for code, fname in TEMPLATES.items():
        tpl = os.path.join(TPL_DIR, fname)
        atoms = template_atoms(tpl)
        all_teks = set(teks_by_course[code])
        covered = set()
        for a in atoms:
            keys = [a] + atom_credentials(a)
            for k in keys:
                for t in cred_to_teks.get(k, ()):
                    if t in all_teks:
                        covered.add(t)
        missing = sorted(all_teks - covered)
        pct = 100 * len(covered) / len(all_teks) if all_teks else 0

        lines += [
            f"## {code} \u2014 {fname}",
            "",
            f"- Atoms in template: **{len(atoms)}** ({len(set(atoms))} unique)",
            f"- TEKS in framework: **{len(all_teks)}**",
            f"- TEKS covered: **{len(covered)}** ({pct:.0f}%)",
            f"- TEKS uncovered: **{len(missing)}**",
            "",
        ]
        if missing:
            lines.append("### Uncovered TEKS")
            lines.append("")
            for t in missing:
                lines.append(f"- `{t}` \u2014 {teks_text.get(t, '')[:140]}")
            lines.append("")
        else:
            lines.append("_Full coverage._\n")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
