#!/usr/bin/env python3
"""Coverage report: template lessons -> crosswalk -> state standards.

For each template, determines which state standards are covered by at
least one lesson and which are uncovered. A standard is "covered" if
any lesson in the template maps (via crosswalk.csv) to that standard.

Usage:
    python3 scripts/coverage_report.py                  # defaults: Texas
    python3 scripts/coverage_report.py --state texas
"""
import argparse
import csv
import os
import re
from collections import defaultdict

BASE = "/home/user/CTE"
PATHWAY_DIR = f"{BASE}/library/health-science"


def load_standards_by_course(framework_csv):
    by_course = defaultdict(list)
    texts = {}
    names = {}
    with open(framework_csv) as f:
        for r in csv.DictReader(f):
            by_course[r["course_code"]].append(r["standard_code"])
            texts[r["standard_code"]] = r["standard_text"]
            names[r["course_code"]] = r["course_name"]
    return by_course, texts, names


def load_lesson_to_standards(crosswalk_csv):
    lesson_to_std = defaultdict(set)
    with open(crosswalk_csv) as f:
        for r in csv.DictReader(f):
            lesson_to_std[r["lesson_id"]].add(r["standard_code"])
    return lesson_to_std


def template_lessons(template_path):
    with open(template_path) as f:
        txt = f.read()
    return re.findall(r"lesson_id:\s+([\w\.\-]+)", txt)


def template_course_code(template_path):
    with open(template_path) as f:
        txt = f.read()
    m = re.search(r'^course_code:\s*"?([\w\.\-]+)"?', txt, re.M)
    return m.group(1) if m else None


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--state", default="texas")
    args = p.parse_args()

    framework = f"{PATHWAY_DIR}/crosswalks/{args.state}/state-framework.csv"
    crosswalk = f"{PATHWAY_DIR}/crosswalks/{args.state}/crosswalk.csv"
    tpl_dir = f"{PATHWAY_DIR}/templates/{args.state}"
    out = f"{PATHWAY_DIR}/crosswalks/{args.state}/coverage-report.md"

    standards_by_course, std_text, course_names = load_standards_by_course(framework)
    lesson_to_std = load_lesson_to_standards(crosswalk)

    templates = {}
    for fname in sorted(os.listdir(tpl_dir)):
        if not fname.endswith(".md") or fname.startswith("_"):
            continue
        code = template_course_code(os.path.join(tpl_dir, fname))
        if code:
            templates[code] = fname

    header = f"# health-science ({args.state}) — Standards Coverage Report"
    lines = [
        header,
        "",
        "Derived coverage per course via the lesson → crosswalk → standard chain.",
        "Generated by `scripts/coverage_report.py`.",
        "",
    ]

    for code, fname in templates.items():
        tpl = os.path.join(tpl_dir, fname)
        lessons = template_lessons(tpl)
        all_std = set(standards_by_course.get(code, []))
        covered = set()
        for lesson in lessons:
            for std in lesson_to_std.get(lesson, ()):
                if std in all_std:
                    covered.add(std)
        missing = sorted(all_std - covered)
        pct = 100 * len(covered) / len(all_std) if all_std else 0

        lines += [
            f"## {code} — {course_names.get(code, '')} ({fname})",
            "",
            f"- Lessons in template: **{len(lessons)}** ({len(set(lessons))} unique)",
            f"- Standards in framework: **{len(all_std)}**",
            f"- Standards covered: **{len(covered)}** ({pct:.0f}%)",
            f"- Standards uncovered: **{len(missing)}**",
            "",
        ]
        if missing:
            lines.append("### Uncovered standards")
            lines.append("")
            for t in missing:
                lines.append(f"- `{t}` — {std_text.get(t, '')[:140]}")
            lines.append("")
        else:
            lines.append("_Full coverage._\n")

    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
